tap "caskroom/cask"

# Brew

## Development

brew "ag"
brew "cloc"
brew "git"
brew "ncdu"
brew "tig"

## Utils

brew "antigen"
brew "hugo"
brew "tree"

# Cask

cask_args appdir: "/Applications"

## Android

cask "android-sdk"
cask "android-studio"
cask "intel-haxm"
cask "intellij-idea-ce"
cask "java"

## Utils

cask "1password"
cask "dropbox"
cask "google-chrome"
cask "macvim"
cask "spotify"
cask "transmission"
cask "tunnelbear"
cask "vlc"

# Mac App Store

mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "TickTick", id: 966085870
mas "Unarchiver", id: 425424353
