tap "homebrew/cask"
tap "homebrew/cask-versions"

# Brew

## Development

brew "ag"
brew "cloc"
brew "git"
brew "ncdu"
brew "tig"

## Utils

brew "antigen"
brew "hugo"
brew "tree"

# Cask

cask_args appdir: "/Applications"

## Android

cask "android-sdk"
cask "android-studio"
cask "adoptopenjdk8"

## Utils

cask "google-chrome"
cask "macvim"
cask "spotify"
cask "transmission"
cask "tunnelbear"
cask "vlc"

# Mac App Store

mas "1Password", id: 1333542190
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "TickTick", id: 966085870
mas "Unarchiver", id: 425424353
