open-store-pages:
	open "macappstore://itunes.apple.com/app/id409201541"

open-store-pixelmator:
	open "macappstore://itunes.apple.com/app/id407963104"

open-store-reeder:
	open "macappstore://itunes.apple.com/app/id880001334"

open-store-the-unarchiver:
	open "macappstore://itunes.apple.com/app/id425424353"

open-store-wunderlist:
	open "macappstore://itunes.apple.com/app/id410628904"

install-command-line-tools:
	xcode-select --install

install-brew:
	open "http://brew.sh"

install-brew-packages:
	brew tap homebrew/brewdler
	brew brewdle
